theme: jekyll-theme-minimal
plugins:
    - jekyll-redirect-from
collections:
    apex_of_creation:
        title: Apex of Creation
        series_url: /books/apex_of_creation
        output: true
        permalink: /books/:collection/:name
    deathworld_origins:
        title: Deathworld Origins
        series_url: /books/deathworld_origins
        output: true
        permalink: /books/:collection/:name
collections_dir: books
defaults:
  - scope:
        path: ""
    values:
        layout: default